### ISSUE TITLE
Uncorrect keys when using AZERTY French keyboard.

### ISSUE THREAD

**Issue by delopa** [Nurrl/Dckuino.js#23]
I'm french (sorry for my bad english), and I'm using an AZERTY keyboard and I've got some problems.
The code is not correctly executed, So I convert in QUERTY, the same.

**Comment by Nurrl** [comment]
Hi @delopa (I'm French too, but for the general understanding I'll talk English ;D),
Did you copied and pasted the code or did you used the download button ? ;D

**Comment by delopa** [comment]
Copy / paste, why ?

**Comment by Nurrl** [comment]
Yes, this is because as you might know, the code is using the default Arduino Keyboard library(Which only works for English QWERTY layouts), but if you use the **Download Sketch** button, you can select the locale (For you **fr_FR**), and this will bundle a wonderful modified Keyboard library for your locale ;D

**Comment by Nurrl** [comment]
Tell me if this doesn't worked, I'll reopen the issue.. ;D

**Comment by Plazmaz** [comment]
Perhaps disabling copy/paste from the box would be smart when the locale is changed @Nurrl

**Comment by delopa** [comment]
It works on Firefox ! Thanks !
But `Start download` didn't work on chrome (why ?)

**Comment by Nurrl** [comment]
@Plazmaz Yes it would be cool simply to remake the GUI, and the core to make it modular as I said here : #22.

@delopa I don't know, I'll try to fix it when I'll rebuild the GUI ;D
